spring:
  application:
    name: sharingsphere

  shardingsphere:
    enabled: true
    datasource:
      names: ds1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo_ds_0?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: root
        password: root
        hikari:
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
    sharding:
      tables:
        # 单库-分表 standard表达式 配置分表方案
        activity_booking_record:
          actual-data-nodes: ds1.activity_booking_record_00$->{0..7}
          table-strategy:
            standard:
              sharding-column: business_id
              precise-algorithm-class-name: com.cowell.gulosity.web.rest.util.BusinessIdShardingAlgorithm
            key-generator:
              column: id
              type: SNOWFLAKE
    props:
      sql:
        show: true

server:
  port: 8089
